# .github/workflows/ci.yml
name: SQA Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup uv menggunakan action resmi Astral
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        # Menarik pytest dan pytest-cov dari pyproject.toml
        run: uv sync --dev

      - name: Run Tests with Coverage
        # Menjalankan tes dan menampilkan persentase kode yang ter-cover
        run: uv run pytest test_main.py -v --cov=main
